baseURL = 'https://citadelhack.github.io/'
languageCode = 'en-us'
title = 'The Citadel Hacker'
theme = 'hello-4s3ti'

[params]
  defaultTheme = "dark"
  backgroundEffects = true
  showPosts = true
  tags = true
  ReadMoreText = true
  fontAwesome = { KitURL = "https://kit.fontawesome.com/0ed5cec925.js" }
  ShowReadingTime = true
  LastModDisplay = true
  logo = { logoText = "The Citadel Hacker", logoCursorColor = "#ffffff" }
  footer = { socialIcons = true }

[[params.social]]
  name = "github"
  url = "https://github.com/citadelhack"
[[params.social]]
  name = "discord"
  url = "https://discord.gg/acnDSfp3fh"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "cyber_team"
    name = "Cyber Team"
    url = "/cyber_team/"
    weight = 3

  [[menu.main]]
    identifier = "cyber_club"
    name = "Cyber Club"
    url = "/cyber_club/"
    weight = 2

  [[menu.main]]
    identifier = "resources"
    name = "Resources"
    url = "/resources/"
    weight = 4

  [[menu.main]]
    identifier = "cryptography"
    name = "Cryptography"
    url = "/resources/cryptography"
    parent = "resources"
